name = "SuperLU"
uuid = "149cae9a-b337-42bd-ac98-00096b14e8a3"
authors = ["Kyungmin Lee <kyungmin.lee.42@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuperLU_jll = "f391fee2-5786-5cc9-9662-0e362ec949e2"

[extras]
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SuiteSparse"]